project:
  type: website
  output-dir: docs

website:
  title: "Max Kuhn"
  repo-url: https://github.com/tidymodels/tidymodels.org
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: education.qmd
        text: Education
      - href: experience.qmd
        text: Experience
      - href: research/index.qmd
        text: Research
      - href: software.qmd
        text: Software

format:
  html:
    theme: [simplex, kuhn.scss]
    mainfont: 'Libre Franklin'

