---
title: "Education"
toc: true
---

## Ph. D. in Biostatistics 

Virginia Commonwealth University, Department of Biostatistics (1994 - 1998)
Richmond, VA

Dissertation topic: _Incorporating Noise Factors into Survival and Generalized Linear Models_

Advisors:  Dr. Hans Carter, Dr. Raymond Myers

Abstract: 

> Recent advances in quality technology have led statisticians to consider a variable's variation as well as it's mean. Response surface models have been developed to incorporate the effects of variables that have an influence on variance ("noise" and "dispersion} factors) into the design, analysis and interpretation of an experiment. Although there has been a large body of work dealing with normally distributed endpoints, little has been done for non-normal data. Our research focuses on the development of these methodologies for time to response data that are possibly censored, members of the exponential family of distributions which may have nonlinear expectation and variance functions, such as the Poisson and Binomial, and distributions specified only through their first two moments. The development of mean and variance models for responses whose first two moments are nonlinear in the noise factors is accomplished using first and second order Taylor series approximations to the two models. In certain special cases, exact representations of the mean and variance models can be found if fully parametric assumptions are made on the noise factors.
> 
> The research is illustrated through an example to assess the effect of tumor age on the optimal two drug combination of CTX and 5-FU in combating murine L1210 leukemia. Tumor age, a factor usually unknown at the time of treatment, can cause variation in survival time. Models for both the mean and variance are used to find treatment combinations that are robust to the variation caused by tumor age and yield more consistent treatments, when tumor age is not known. Additional examples involve the modeling of circuit board wafer resistivity, which is typically skewed, the proportion of defective chips on a large scale production circuit board, and the number of bull spermatozoa surviving long term freezing.


## B.S in Mathematics

Virginia Commonwealth University, Department of Mathematics (1989 - 1994)
Richmond, VA

